### ISSUE TITLE
Database connection failed

### ISSUE THREAD

**Issue by Makermc** [answerdev/answer#89]
![image](https://user-images.githubusercontent.com/35621758/201816859-65222820-8b36-4bd3-b346-a4504c9892cb.png)
这里填写AWS RDS会连接失败

**Comment by Makermc** [comment]
背景是在一台EC2上通过docker运行了该项目
1. 在EC2上通过`mysql -h <host> -u <user> -p`是可以联通的
2. 同步步骤一中，`show databases;`可以确定并没有创建同名数据库
3. 还未测试容器内链接数据库，不清楚这个镜像的构建情况，试了下命令行都没有...
4. 目前采用SQLite数据库在运行
![image](https://user-images.githubusercontent.com/35621758/201862378-bb222bf8-04d7-457b-992b-816ae8133091.png)

**Comment by Makermc** [comment]
另外，建议在INSTALL.md中说明一下，mysql需要手动操作。
Have a nice day!

**Comment by nkev** [comment]
I'm on MacBook M1 Ventura and getting the same issue in SQLite, which requires no DB server setup:

<img width="670" alt="image" src="https://user-images.githubusercontent.com/5410916/220794167-ae6951c4-4a17-42e5-bd7d-396f01b0c0ec.png">

The error in the terminal is:
> 2023-02-23 11:26:36.977	ERROR	/tmp/runner/work_{{.Task.Slot}}/answer/answer/internal/base/data/data.go:45	create database dir failed: mkdir /data: read-only file system
connection database failed: unable to open database file: out of memory (14)

(I have 12GB free memory and the `answer_1.0.5_macOS_arm64` folder has read/write permission for everyone)

**Comment by nkev** [comment]
@LinkinStars I'm using binary

**Comment by nkev** [comment]
@LinkinStars Thanks for the support. It obviously works if you init inside /tmp/* but that's not realistic. Most people will want the DB file somewhere inside the same folder as the answer executable, like in the binary installation instructions on your website. Please also note that even when the db is in the /tmp folder, in the last step, the link below is dead:

<img width="526" alt="image" src="https://user-images.githubusercontent.com/5410916/221133625-e924b085-0569-4057-8464-668603cc1805.png">


> 1. did you manually create a data directory such as /tmp/answer and give it read and write permissions 
>2. whether the sqlite data storage directory is configured under the data directory such as /tmp/answer/answer.db
>3. whether answer has permission to read and write to the directory

No, because your website instructions don't say to do these steps. But I did those steps anyway and
the error persists.

Your binary installation instructions just say run `./answer init -C ./answer-data/` and then run `./answer run -C ./answer-data/`. Does it work for you when you download the binary to your `~/downloads` folder and then run these 2 commands inside the `answer_1.0.5_macOS_arm64 ` folder? This is what most people will do to trial the application.

**Comment by nkev** [comment]
Sorry, my mistake. I got it working. For the benefit of others,  when you get to the installations step of specifying the database file, don;t forget to put a dot before the path (to denote current app directory), like this `./answer-data/answer.db`

**Comment by hueralin** [comment]
> 明白了，对于 MySQL，Answer **不会主动的创建数据库**，你需要手动的创建一个数据库，然后在安装的时候指定你创建的数据库名称。因为我们考虑到并非所有 mysql 账户都有创建数据库的权限，很多情况下用户并不会提供如此高权限的账户，所以我们还是将创建数据库的工作交给人工自己去完成。
> 
> Got it. For Mysql, `Answer` does not create the database proactively, so you need to create the corresponding database manually first.

感谢！
